export const airlinesList = [
  {
    group: "Alliances",
    airlines: ["Oneworld", "SkyTeam", "Star Alliance"],
  },
  {
    group: "Airlines",
    airlines: [
      "Aegean",
      "Air Algerie",
      "Air Cairo",
      "Air Dolomiti",
      "Air Europa",
      "Air France",
      "Air Serbia",
      "AJet",
      "American",
      "Austrian",
      "Azores Airlines",
      "British Airways",
      "Brussels Airlines",
      "Bulgaria Air",
      "China Eastern",
      "EgyptAir",
      "Emirates",
      "Ethiopian",
      "Etihad",
      "Garuda Indonesia",
      "Gulf Air",
      "Iberia",
      "ITA",
      "KLM",
      "Korean Air",
      "Kuwait Airways",
      "LOT",
      "Lufthansa",
      "Malaysia Airlines",
      "MEA",
      "Oman Air",
      "Pakistan International Airlines",
      "Pegasus",
      "Qantas",
      "Qatar Airways",
      "Royal Air Maroc",
      "Royal Jordanian",
      "RwandAir",
      "Saudia",
      "SunExpress",
      "SWISS",
      "Tap Air Portugal",
      "TAROM",
      "Transavia",
      "Tunisair",
      "Turkish Airlines",
      "Virgin Australia",
      "Vueling",
    ],
  },
];
